name: My Coding Stats

on:
  schedule:
    - cron: '0 9 * * 1'  #Monday 4/5am central
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_LANGUAGE: True
          SHOW_PROJECTS: True
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_OS: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_PROFILE_VIEWS: False
          SHOW_TOTAL_CODE_TIME: True
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SYMBOL_VERSION: 2